### ISSUE TITLE
str_replace_missing() instead of str_replace_na() ?

### ISSUE THREAD

**Issue by cecoeco** [TidierOrg/TidierStrings.jl#16]
Since julia does not use NA like R should we rename the str_replace_na() function to str_replace_missing()?

According to this documentation julia's missing is equivalent to R's NA:
https://docs.julialang.org/en/v1/manual/missing/

**Comment by drizk1** [comment]
Yes this is a great idea. 

This was a mistake on my end and it should've been that all along. 

I think we can rename them and fix the docstrings but leave `str_replace_na` available for a release or 2 with a print message saying it will be depreciated and to use `str_replace_missing` instead

**Comment by cecoeco** [comment]
Sounds great. There isnt a str_replace_na implemented in julia yet, so i'll just add str_replace_missing because there is no str_replace_na to replace, is that okay?

**Comment by drizk1** [comment]
Oh that's perfect yes thank you!
