### ISSUE TITLE
add ability for `str_extract_all` to get capture groups instead of matches 

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierStrings.jl#21]
Advent strikes again!

I modified the `str_extract_all` function to optionally return capture groups instead of just the matches: 

```
function str_extract_all(string::AbstractString, pattern::Union{String, Regex}; captures::Bool=false)
    regex_pattern = isa(pattern, String) ? Regex(pattern) : pattern
    to_missing(l) = [ifelse(isnothing(c), missing, c) for c in l]
    matches = captures ?
        [to_missing(m.captures) for m in eachmatch(regex_pattern, string)] :
        [String(m.match) for m in eachmatch(regex_pattern, string)]
    return isempty(matches) ? missing : matches
end
```

This version returns `missing` when there is no capture group rather than the default `nothing` - not sure what you want the default to be but its an easy change - I can make a PR if this looks good to you

**Comment by drizk1** [comment]
Returning missing is def better. Looks good to me. Ty. We can immediately for ur advent journey id you'd like as well

**Comment by rdboyes** [comment]
PR here: https://github.com/TidierOrg/TidierStrings.jl/pull/22

**Comment by drizk1** [comment]
Fixed version .2.5 is on its way to the registry. Thx for the catch  n fix
