### ISSUE TITLE
Typos in "Supported Functions" article

### ISSUE THREAD

**Issue by etiennebacher** [TidierOrg/TidierStrings.jl#6]
Hello, just quickly going through the docs, it seems that markdown syntax is applied on function names, which is why there are italics on some parts of the words:

![image](https://github.com/TidierOrg/TidierStrings.jl/assets/52219252/7712afd4-7db7-4c77-9a59-5ac745f3498a)

**Comment by drizk1** [comment]
Hey thanks for catching that. I'll have an updated version up within a day or so.

**Comment by drizk1** [comment]
the documentation has been updated! hope you enjoy Tidier.jl!
